spring:
  application:
    name: gpt-chat-bot
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  datasource:
    url: 'jdbc:mysql://localhost:3306/gpt-chat-bot'
    username: root
    password:
  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update


jwt:
  secret: 'secret'
server:
  error:
    include-stacktrace: never
